### PR TITLE
[SE-4575] merge annoto master

### PR DESCRIPTION
**Pull request by gabor-boros**
Pull `annoto/xblock-in-video-collaboration` upstream master changes.

**Dependencies**: None

**Sandbox URL**: TBD - sandbox is being provisioned.

**Merge deadline**: None

**Testing instructions**:

* Check annoto [xblock is added](https://studio.stage.campus.gov.il/container/block-v1:OpenCraft+CS101+2021_T1+type@vertical+block@c3e360f864db472da0bf071835d728d5)
* Check the [page loads fine](https://preview.stage.campus.gov.il/courses/course-v1:OpenCraft+CS101+2021_T1/courseware/21efd00c618c4ecaa2666be3e445778f/1d8df78bc3eb424a9864135c978a1159/1?activate_block_id=block-v1%3AOpenCraft%2BCS101%2B2021_T1%2Btype%40vertical%2Bblock%40c3e360f864db472da0bf071835d728d5) -- annoto xblock should produce no content

**Author notes and concerns**:

N/A

**Reviewers**
- [ ] @jvdm

### CODE REVIEW

**Comment by jvdm** [comment]
:+1:

- [x] I tested this: Verified XBlock loading and deployment.
- [x] I read through the code. This is a merging PR, assuming upstream changes are stable.
- ~[ ] I checked for accessibility issues.~ N/A
- ~[ ] Includes documentation.~ N/A
- ~[ ] I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.~ N/A

**Review by jvdm — APPROVED** [review]
:+1:

- [x] I tested this: Verified XBlock loading and deployment.
- [x] I read through the code. This is a merging PR, assuming upstream changes are stable.
- ~[ ] I checked for accessibility issues.~ N/A
- ~[ ] Includes documentation.~ N/A
- ~[ ] I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.~ N/A

**Comment by gabor-boros** [comment]
@annoto-campus Could you please take a look at this PR?

**Comment by gabor-boros** [comment]
@annoto-campus Would you have some time to check this PR?

**Comment by HenEytan** [comment]
[SE-4575] merge annoto master

**Pull request merged**
