### PR TITLE
Merge upstream version changes.

### PR DESCRIPTION
**Pull request by Kelketek**

### CODE REVIEW

**Comment by Kelketek** [comment]
@annoto-campus This contains the changes from upstream. It will need to be merged before deployment to stage or production can happen.

**Comment by Kelketek** [comment]
@swallage Could you review this PR and verify that it contains what's required? It's just a dump of all upstream changes with a small tweak to resolve a very straightforward merge conflict. Please don't review any further than obvious breakage.

**Review by samuelallan72 — APPROVED** [review]
@Kelketek :+1:

- [x] I tested this: checked that the changes here match upstream (sans the profile/name/photo which are required to be excluded
- [x] I read through the code
- [ ] NA I checked for accessibility issues
- [ ] NA Includes documentation

**Comment by Kelketek** [comment]
@HenEytan Are you able to merge this today? We'd like to get it deployed for a course next week.

**Comment by Kelketek** [comment]
@HenEytan Checking in here-- we are still hoping to get this deployed as soon as possible. Thank you.

**Pull request merged**
